<?php
/**
 * Created by PhpStorm.
 * User: Hash
 * Date: 21-08-2015
 * Time: 23:21
 */

namespace app;


use Illuminate\Database\Eloquent\Model;

class Device extends Model{

/*deviceType:<integer> (1=iOS, 2=Android)
pushNotificationDeviceId:<string>
DeviceRequest {
id (integer, optional): Identifier of this device.,
uuid (string, optional): Unique ID generated by the device.,
platform (string, optional): Platform information of the device.,
version (string, optional): Version information of the device.,
model (string, optional): Model information of the device.,
extra (string, optional): Extra information from the device.
}


    {
        "error": [
    {
        "context": null,
      "message": "Failed to register user device.\n1. [uuid] : UUID cannot be blank.\n",
      "code": 500
    }
  ]
}*/

}